apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: amazon/retail-store-catalog:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: "catalog-db" # adjust if using external DB
        - name: DATABASE_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
